
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // CLI operations (introspect, migrate, studio) use the direct connection —
    // Supabase's pooled/pgbouncer connection (DATABASE_URL) hangs for these.
    // The running app still connects via DATABASE_URL (see lib/db.ts).
    url: env("DIRECT_URL"),
  },
});
